### ISSUE TITLE
S1.9 Consumer | Interaction With Preferences and Services | Smart Speaker or non-traditional interface

### ISSUE THREAD

**Issue by DanHugoDanHugo** [InnovateForVegas/ov-open-transit#15]
**Epic**: #6 

#### Card

As a Consumer, I would like to interact with my transit preferences and information using a Smart Speaker or other non-browser interfaces.

#### Conversation

There will be opportunities into the future to provide Consumers with additional methods of interaction with their transit use and data, to fit into their individual workflows. Integration with a device such as a Smart Speaker not only provides convenient access to personalized transit information for any user with that access method, but it also extends access to these data to a Consumer with impaired vision, in a usable way. A side effect, design for flexible application such as a Smart Speaker, implies design for flexible application for other devices, and thus service to more Consumers in more modes.

#### Confirmation

- [ ] A Consumer is able to receive schedule, route, and other pertinent information about their transit use via a Smart Speaker with voice-activated interface.
- [ ] A Consumer is able to receive a general update on demand of their transit plans on the current day.
- [ ] A Consumer is able to receive a specific update for a particular day in the future.

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
