### ISSUE TITLE
S1.3 Consumer | Feedback to transit company | any time

### ISSUE THREAD

**Issue by DanHugoDanHugo** [InnovateForVegas/ov-open-transit#9]
**Epic**: #6 

#### Card

As a Consumer, I would like to be able to provide feedback to the company regarding my transit experience at any particular time and place.

#### Conversation

A Consumer may encounter good or bad factors en route to their first stop, waiting, boarding, riding, exiting, waiting for another bus for continued travel, locating a bike share, waiting at an unfamiliar or distal stop, etc.

#### Confirmation

- [ ] Consumer is presented with a context-aware feedback interface, which varies based on whether approaching a stop, at a stop waiting, boarding/riding/exiting a vehicle, attempting to check out a bicycle, and so on, to provide positive or negative feedback, comments, photographic and potentially other information for the Company to process.
- [ ] Consumer may need to select context for feedback, with accessible and localized interface for that selection. While automatic selection is intriguing, feedback about a bus stop after boarding a bus would become frustrating if the feedback context is auto-selected as Bus, for example, rather than But Stop.
- [ ] Consumer is able to provide feedback and receive acknowledgment of receipt, as well as a method to continue engagement with follow-up, including resolution of any issues (or similar in the case of positive feedback)

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
